"""Portable BASISServe runtime configuration and communication primitives."""

from basisserve.core.attention_tp_layout import AttentionTPLayout
from basisserve.core.gqa_vo_svdllm import (
    FullOInputCovariance,
    GQAHeadwiseOInputCovariance,
    GQAIdentityOInputCovariance,
    GQAOInputCovariance,
    GQAVOGroupFactors,
    GQAVOLayout,
    GQAVOLayerFactors,
    GlobalOWhitenedError,
    OInputActivationSamples,
    activation_whitened_o_reconstruction_error,
    factorize_gqa_vo_activation_whitened,
    factorize_gqa_vo_headwise_activation_whitened,
    global_o_activation_whitened_errors,
    refine_gqa_vo_global_joint_linear,
    validate_projection_shapes,
)
from basisserve.core.low_rank_config import LowRankKVConfig
from basisserve.core.global_rank_sensitivity import (
    PairwiseRankSwap,
    adjacent_pairwise_rank_swaps,
    logits_logsumexp,
    teacher_kl_sum,
)
from basisserve.core.tp_output import (
    CommunicationEstimate,
    DenseRowParallelOutput,
    DistributedLowRankOutputFactors,
    HadamardLowRankAllReduceOutput,
    LowRankAllReduceOutput,
    LowRankOutputFactors,
    PrivateAllGatherOutput,
    factorize_output_weight,
    factorize_output_weight_with_hadamard_basis,
    factorize_row_parallel_weight_distributed,
    hadamard_basis_columns,
    resolve_rank,
)
from basisserve.core.topk_all_gather import (
    FixedTopKAllGatherOutput,
    fixed_topk_count,
    fixed_topk_packet_bytes,
    pack_fixed_topk,
    unpack_fixed_topk,
)

__all__ = [
    "AttentionTPLayout",
    "CommunicationEstimate",
    "DenseRowParallelOutput",
    "DistributedLowRankOutputFactors",
    "FullOInputCovariance",
    "FixedTopKAllGatherOutput",
    "GQAHeadwiseOInputCovariance",
    "GQAIdentityOInputCovariance",
    "GQAOInputCovariance",
    "GQAVOGroupFactors",
    "GQAVOLayout",
    "GQAVOLayerFactors",
    "GlobalOWhitenedError",
    "HadamardLowRankAllReduceOutput",
    "LowRankAllReduceOutput",
    "LowRankKVConfig",
    "LowRankOutputFactors",
    "PrivateAllGatherOutput",
    "PairwiseRankSwap",
    "OInputActivationSamples",
    "adjacent_pairwise_rank_swaps",
    "factorize_output_weight",
    "factorize_output_weight_with_hadamard_basis",
    "activation_whitened_o_reconstruction_error",
    "factorize_gqa_vo_activation_whitened",
    "factorize_gqa_vo_headwise_activation_whitened",
    "global_o_activation_whitened_errors",
    "refine_gqa_vo_global_joint_linear",
    "factorize_row_parallel_weight_distributed",
    "fixed_topk_count",
    "fixed_topk_packet_bytes",
    "hadamard_basis_columns",
    "logits_logsumexp",
    "pack_fixed_topk",
    "resolve_rank",
    "teacher_kl_sum",
    "unpack_fixed_topk",
    "validate_projection_shapes",
]
from .sequential_rank_exchange import (
    RankMarginal,
    collect_rank_marginals,
    form_exact_budget_pairs,
    paired_risk_summary,
    select_domain_robust_pair,
)
